name: meditap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_custom_clippers: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  image_picker: ^1.0.8
  file_picker: ^8.0.0
  modal_progress_hud_nsn: ^0.5.0
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.0.7
  lottie: ^3.0.0
  equatable: ^2.0.5
  flip_card_swiper: ^1.0.0
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  easy_date_timeline: ^1.1.2

dev_dependencies:
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Kidney img.png
    - lib/assets/avi.jpg